### ISSUE TITLE
Try out cookiecutter template

### ISSUE THREAD

**Issue by syoh** [UCSB-PSTAT/gradescope-ottergrader#1]
I created a cookiecutter template for creating the dual directory structure. Could you try it out and lmk how it goes?

You can the following line from your command line:
`cookiecutter --checkout cookiecutter gh:UCSB-PSTAT/gradescope-ottergrader`

Please report any problem with comments below

**Comment by joshuaybang** [comment]
I wasnt' sure what to type for the following questions: "github_personal_access_token", "base_jupyter_notebook_image", "jupyter_notebook_port". I just typed what's in the bracket, and this is the error I got.

<img width="1033" alt="error" src="https://user-images.githubusercontent.com/38017251/110227690-efa6e180-7eaf-11eb-81aa-ce3990e23428.png">

**Comment by syoh** [comment]
Did you choose macOS as your choice to the first question?

**Comment by joshuaybang** [comment]
Yes, I did.

**Comment by syoh** [comment]
Ok, the mac portion has a bug then (I don't have a mac to test on). I removed some stuff. Could you try again? You can choose the defaults for access token, etc

**Comment by joshuaybang** [comment]
Yep, now it works perfectly.

**Comment by JiajingZ** [comment]
Yeah, it works on my side too.
